# .github/workflows/daily_analysis.yml (Riscritto)

name: Daily Trading Analysis

on:
  schedule:
    # Run every weekday at 4:30 PM EST (21:30 UTC) - after market close
    - cron: '30 21 * * 1-5'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      ticker:
        description: 'Stock ticker to analyze'
        required: false
        # --- MODIFICA 1: Ticker di default aggiornato a VXX ---
        default: 'VXX'

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Run analysis
      env:
        # --- MODIFICA 2: Rimosso EODHD_API_KEY, non più necessario ---
        # EODHD_API_KEY: ${{ secrets.EODHD_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        # --- MODIFICA 3: Ticker di fallback aggiornato a VXX ---
        TICKER: ${{ github.event.inputs.ticker || 'VXX' }}
      run: |
        python main_analysis.py
    
    - name: Commit and push results
      env:
        # --- MODIFICA 4: Ticker di fallback aggiornato a VXX ---
        TICKER: ${{ github.event.inputs.ticker || 'VXX' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Aggiungiamo al commit la cartella specifica del ticker
        # NOTA: GitHub Actions potrebbe avere problemi con caratteri speciali come '^'.
        # Se il commit fallisce, potrebbe essere necessario mappare 'VXX' a VXX' come nome di cartella.
        # Per ora, lasciamo così che è più diretto.
        git add data/"${{ env.TICKER }}"/
        
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Update analysis results for ${{ env.TICKER }} - $(date -u +'%Y-%m-%d %H:%M')"
          git push
        else
          echo "No changes to commit for ${{ env.TICKER }}."
        fi
    
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      env:
        # --- MODIFICA 5: Ticker di fallback aggiornato a VXX ---
        TICKER: ${{ github.event.inputs.ticker || 'VXX' }}
      with:
        name: analysis-results-${{ env.TICKER }}
        path: |
          data/${{ env.TICKER }}/signals.csv
          data/${{ env.TICKER }}/signals_latest.json
          data/${{ env.TICKER }}/backtest_results.json
          data/${{ env.TICKER }}/analysis_summary.json
        retention-days: 30
    
    - name: Deploy to Streamlit Cloud
      if: success()
      run: |
        echo "Dashboard will auto-update on Streamlit Cloud"
        echo "Visit: https://kriterion-quant.streamlit.app"
